### ISSUE TITLE
Project Milestone 1 Tasks Example

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textAnalysis-Hub#161]
- [ ] Review the [Semester Project GuidelinesLinks to an external site.](https://github.com/newtfire/textAnalysis-Hub/blob/main/projectGuidelines.md) posted on the textAnalysis-Hub with your team and establish your team's research questions.

- [ ] Plan to get Dr. B involved in the project chat or a meeting--what questions do you have/need help with?

- [ ] Make a plan for how documents will be organized, and how you'll be working together (using branches, etc). Prepare and organize your collection(s) of documents for analysis in your team repo. 

- [ ] Prepare a docs/ directory and set up GitHub Pages

- [ ] Try initiating a Python project in your repo so it can read your collection of documents.
- [ ] Copy in [Dr. B's .gitignore from the textAnalysis-HubLinks to an external site.](https://github.com/newtfire/textAnalysis-Hub/blob/main/.gitignore) to your repo, and make sure everyone pulls this in to their local repos. Ideally, do this  before anyone pushes Python files. (This screens out local Python environment files so your team can share code without tangling up local Pycharm configurations.)

Suggestion: you might want the following folder structure in your repo:
   * python 
   * textFiles
   * docs (for GitHub Pages)
   * xml (for textFiles converted to XML)

- [ ] When writing Python, try creating a Pycharm project on hte whole GitHub repo, and just browse into the python directory for your python script. Be careful with your file associatons. Once you've set these up, it'll be easy to continue.

- [ ] Inspect the collection and be sure you understand its structure, how even/regular it is, what kinds of data it contains and what it's missing. Report back on that in this milestone. 

- [ ] Launch the GitHub Pages project website: Develop a "splash page" or a start page for the project.
